"""Verdict sounds for the scanner.

A bar is loud and the operator is often looking at the customer rather
than the screen, so every scan gets an audible verdict alongside the
banner: a bell for ALLOWED, a buzzer for DENIED or an unreadable scan.

Playback is fire-and-forget and never raises. A PC with no sound card,
no audio device, or a missing .wav must degrade to a silent scanner —
never to a scanner that stops working. Every failure here is swallowed
on purpose.

The .wav files are generated by make_sounds.py and bundled into the
exe via BarScanner.spec.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

ALLOWED_WAV = "allowed.wav"
DENIED_WAV = "denied.wav"

# POSIX players, best first. Windows never gets here — it uses winsound
# from the standard library. This list exists so the app is testable on
# the Linux dev machine, where the exe is built but not run.
_POSIX_PLAYERS = ("paplay", "pw-play", "aplay", "afplay")

_players: list[subprocess.Popen] = []
_posix_cmd: list[str] | None = None
_resolved = False


def _resource_path(rel: str) -> str:
    """Resolve a bundled resource path.

    Deliberately duplicated from cac_gui._resource_path rather than
    imported: cac_gui imports this module, and importing back would be
    circular. It's three lines, and this module stays standalone."""
    base = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base, "sounds", rel)


def _posix_player() -> list[str] | None:
    """First available POSIX player command, resolved once per run."""
    global _posix_cmd, _resolved
    if not _resolved:
        _resolved = True
        for name in _POSIX_PLAYERS:
            path = shutil.which(name)
            if path:
                _posix_cmd = [path]
                break
    return _posix_cmd


def _stop_players() -> None:
    """Stop any still-playing sound and drop finished processes.

    Two jobs at once: a fast second scan should cut the first sound off
    rather than play over it, and a long shift shouldn't accumulate
    processes if a player ever hangs on a broken device. Windows gets
    the cut-off behavior free from SND_ASYNC; this is how POSIX matches
    it, so both platforms sound the same."""
    global _players
    for p in _players:
        if p.poll() is None:
            try:
                p.terminate()
            except OSError:
                pass
    _players = [p for p in _players if p.poll() is None]


def _play(filename: str) -> None:
    path = _resource_path(filename)
    if not os.path.isfile(path):
        return
    try:
        if sys.platform == "win32":
            import winsound

            # SND_ASYNC returns immediately, so the scan pipeline is never
            # blocked waiting on audio. A new scan cuts off the previous
            # sound, which is what you want when someone scans twice fast.
            # SND_NODEFAULT keeps Windows from substituting its own system
            # beep if the file can't be played.
            winsound.PlaySound(
                path,
                winsound.SND_FILENAME | winsound.SND_ASYNC | winsound.SND_NODEFAULT,
            )
        else:
            cmd = _posix_player()
            if cmd is None:
                return
            _stop_players()
            _players.append(
                subprocess.Popen(
                    cmd + [path],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            )
    except Exception:
        # Audio is never worth breaking a scan over. See module docstring.
        pass


def play_allowed() -> None:
    """Bell — the scan was approved."""
    _play(ALLOWED_WAV)


def play_denied() -> None:
    """Buzzer — the scan was denied, or the barcode was unreadable."""
    _play(DENIED_WAV)
